apiVersion: apps/v1
kind: Deployment
metadata:
  name: mystique-demo-golang
spec:
  selector:
    matchLabels:
      app: mystique-demo-golang
  replicas: 1
  template:
    metadata:
      labels:
        app: mystique-demo-golang
    spec:
      shareProcessNamespace: true
      containers:
      - name: mystique
        image: uhub.service.ucloud.cn/devsecops/mystique:a5581d5
        imagePullPolicy: Always
      - name: spider
        image: uhub.service.ucloud.cn/devsecops/spider:6.6
        imagePullPolicy: Always
