app:
  type: "spider"
  processors_name: "/opt/app"

input:
  enable: true
  kafka:
    broker: ["117.50.109.103:9092"]
    topic: "analyzer"
    consumer_group: "mystique"

output:
  enable: true
  kafka:
    broker: ["117.50.109.103:9092"]
    topic: "mystique"
