app:
  type: "spider"
  processors_name: "crawler_common"

input:
  enable: false
  kafka:
    broker: ["117.50.109.103:9092"]
    topic: "spider-stdin"
    consumer_group: "mystique"

output:
  enable: true
  kafka:
    broker: ["117.50.109.103:9092"]
    topic: "spider-stdout"
